version: "3"

services:

  database:
    container_name: AuthenticationAppDB
    image: "postgres:15.1-bullseye"
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=auth_app_db
    ports:
      - "5440:5432"
    volumes:
      - auth-app-db-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5440/auth_app_db
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  auth-app-db-data: {}
